name: CI

"on":
  push:
     branches:
        - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up google
        env:
          CLIENT: ${{ secrets.CLIENT }}
          TOKEN_PASSPHRASE: ${{ secrets.TOKEN_PASSPHRASE }}
        run: |
          echo $CLIENT >> tables/client_secret.json
          ./decrypt_secret.sh


      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make tables DMTN-199.pdf'

      - name: No landing page - just put the pdf in github
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m " Build of doc from github action " DMTN-199.pdf tables
          git push
